// File generated by running `flutterfire configure` after setting up your Firebase project
// This is a template - REPLACE with your actual Firebase configuration
// Command: flutterfire configure --project=fuellink-ontario

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'dart:io' show Platform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:123456789:web:xxxxxxxxxxxxxx',
    messagingSenderId: '123456789',
    projectId: 'fuellink-ontario',
    authDomain: 'fuellink-ontario.firebaseapp.com',
    storageBucket: 'fuellink-ontario.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:123456789:android:xxxxxxxxxxxxxx',
    messagingSenderId: '123456789',
    projectId: 'fuellink-ontario',
    storageBucket: 'fuellink-ontario.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:123456789:ios:xxxxxxxxxxxxxx',
    messagingSenderId: '123456789',
    projectId: 'fuellink-ontario',
    storageBucket: 'fuellink-ontario.appspot.com',
    iosBundleId: 'com.fuellink.app',
  );
}
